BEGIN
  DWH.PKG_OSOS_CONSUMPTION_HOURLY.PRC_CON_SUBSCRIBER;
  DWH.PKG_OSOS_CONSUMPTION_HOURLY.PRC_CON_SUBSTATION;
  DWH.PKG_OSOS_CONSUMPTION_HOURLY.PRC_CON_LIGTHING;
  DWH.PKG_OSOS_CONSUMPTION_HOURLY.PRC_UNION_CONSUMPTION;
  DWH.PKG_OSOS_CONSUMPTION_HOURLY.PRC_CON_ARIL;
  DWH.PKG_OSOS_CONSUMPTION_HOURLY.PRC_CON_LUNA;
  DWH.PKG_OSOS_CONSUMPTION_HOURLY.PRC_OSOS_CONSUMPTION_HOURLY;
  DWH.PKG_OSOS_CONSUMPTION_HOURLY.PRC_OSOS_GES_CONSUMPTION;
END;


BEGIN
--  DWH.PKG_OSOS_ACTIVE_ENDEX.PRC_TMP_RDD_DAILYENDEXES;
--  DWH.PKG_OSOS_ACTIVE_ENDEX.PRC_ARIL_ACTIVE_ENDEX;
--  DWH.PKG_OSOS_ACTIVE_ENDEX.PRC_HAYEN_ACTIVE_ENDEX;
--  DWH.PKG_OSOS_ACTIVE_ENDEX.PRC_LUNA_ACTIVE_ENDEX;
--  DWH.PKG_OSOS_ACTIVE_ENDEX.PRC_UNION_ACTIVE_ENDEX;
--  DWH.PKG_OSOS_ACTIVE_ENDEX.PRC_BACK_ENDEX;
--  DWH.PKG_OSOS_ACTIVE_ENDEX.PRC_CONSUMPTION_ACTIVE_ENDEX;
--  DWH.PKG_OSOS_ACTIVE_ENDEX.PRC_TRUNCATE_PARTITION;
  DWH.PKG_OSOS_ACTIVE_ENDEX.PRC_F_MRR_DAILY_ENDEXES;
END;


SELECT * FROM LOGS ORDER BY 4 DESC

alter table DWH.T_UNION_ACTIVE_ENDEX exchange partition APP_ARIL
      with table DWH.T_ARIL_ACTIVE_ENDEX without validation
      
alter table DWH.T_UNION_ACTIVE_ENDEX exchange partition APP_LUNA
      with table DWH.T_LUNA_ACTIVE_ENDEX without validation
      
alter table DWH.F_MRR_DAILY_ENDEXES exchange partition APP_ARIL_LUNA
      with table DWH.T_CONSUMPTION_ACTIVE_ENDEX without validation
      
SELECT * FROM DWH.T_HAYEN_ACTIVE_ENDEX